# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"9\n\rClientRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\x12\x0c\n\x04num3\x18\x03 \x01(\x05\" \n\x0e\x43lientResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"(\n\nDosNumeros\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1b\n\tResultado\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32Y\n\x0e\x43\x65ntralService\x12G\n\x0eProcessNumbers\x12\x19.calculator.ClientRequest\x1a\x1a.calculator.ClientResponse2K\n\nSumService\x12=\n\x0cSumarNumeros\x12\x16.calculator.DosNumeros\x1a\x15.calculator.Resultado2V\n\x0fMultiplyService\x12\x43\n\x12MultiplicarNumeros\x12\x16.calculator.DosNumeros\x1a\x15.calculator.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREQUEST']._serialized_start=32
  _globals['_CLIENTREQUEST']._serialized_end=89
  _globals['_CLIENTRESPONSE']._serialized_start=91
  _globals['_CLIENTRESPONSE']._serialized_end=123
  _globals['_DOSNUMEROS']._serialized_start=125
  _globals['_DOSNUMEROS']._serialized_end=165
  _globals['_RESULTADO']._serialized_start=167
  _globals['_RESULTADO']._serialized_end=194
  _globals['_CENTRALSERVICE']._serialized_start=196
  _globals['_CENTRALSERVICE']._serialized_end=285
  _globals['_SUMSERVICE']._serialized_start=287
  _globals['_SUMSERVICE']._serialized_end=362
  _globals['_MULTIPLYSERVICE']._serialized_start=364
  _globals['_MULTIPLYSERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
