# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculator_pb2 as calculator__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CentralServiceStub(object):
    """Principal
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessNumbers = channel.unary_unary(
                '/calculator.CentralService/ProcessNumbers',
                request_serializer=calculator__pb2.ClientRequest.SerializeToString,
                response_deserializer=calculator__pb2.ClientResponse.FromString,
                _registered_method=True)


class CentralServiceServicer(object):
    """Principal
    """

    def ProcessNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessNumbers,
                    request_deserializer=calculator__pb2.ClientRequest.FromString,
                    response_serializer=calculator__pb2.ClientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.CentralService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculator.CentralService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CentralService(object):
    """Principal
    """

    @staticmethod
    def ProcessNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.CentralService/ProcessNumbers',
            calculator__pb2.ClientRequest.SerializeToString,
            calculator__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SumServiceStub(object):
    """Suma
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SumarNumeros = channel.unary_unary(
                '/calculator.SumService/SumarNumeros',
                request_serializer=calculator__pb2.DosNumeros.SerializeToString,
                response_deserializer=calculator__pb2.Resultado.FromString,
                _registered_method=True)


class SumServiceServicer(object):
    """Suma
    """

    def SumarNumeros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SumarNumeros': grpc.unary_unary_rpc_method_handler(
                    servicer.SumarNumeros,
                    request_deserializer=calculator__pb2.DosNumeros.FromString,
                    response_serializer=calculator__pb2.Resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.SumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculator.SumService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SumService(object):
    """Suma
    """

    @staticmethod
    def SumarNumeros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.SumService/SumarNumeros',
            calculator__pb2.DosNumeros.SerializeToString,
            calculator__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MultiplyServiceStub(object):
    """Multi
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MultiplicarNumeros = channel.unary_unary(
                '/calculator.MultiplyService/MultiplicarNumeros',
                request_serializer=calculator__pb2.DosNumeros.SerializeToString,
                response_deserializer=calculator__pb2.Resultado.FromString,
                _registered_method=True)


class MultiplyServiceServicer(object):
    """Multi
    """

    def MultiplicarNumeros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiplyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MultiplicarNumeros': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiplicarNumeros,
                    request_deserializer=calculator__pb2.DosNumeros.FromString,
                    response_serializer=calculator__pb2.Resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.MultiplyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculator.MultiplyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MultiplyService(object):
    """Multi
    """

    @staticmethod
    def MultiplicarNumeros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.MultiplyService/MultiplicarNumeros',
            calculator__pb2.DosNumeros.SerializeToString,
            calculator__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
